### ISSUE TITLE
Error against template label when label is already defined

### ISSUE THREAD

**Issue by mshahzeb** [grafana/dashboard-linter#27]
[template-job-rule] 'Asterisk - Overview': Dashboard 'Asterisk - Overview' job template should be a labelled 'job'

If you look at the dashboard JSON file - the job temlpate already has a label.
[asterisk-overview.json.zip](https://github.com/grafana/dashboard-linter/files/8082725/asterisk-overview.json.zip)

**Comment by tomwilkie** [comment]
Hi @mshahzeb! Thanks for filling the issue. 

I've improved the error message to make it a little more obvious, but I think the failure is just in capitalisation:

```
[❌] Dashboard 'Asterisk - Overview' job template should be a labelled 'job', is currently 'Job'
```

I went with lowercase 'job' for the labels for convenience really - this was what most mixins I checked out were using.

Out of interest, is the asterix mixin on github somewhere?

**Comment by mshahzeb** [comment]
Hi @tomwilkie Yes it is currently on my feature branch for jsonnet-libs.
https://github.com/grafana/jsonnet-libs/tree/shahzeb/asterisk-mixin/asterisk-mixin
