### ISSUE TITLE
Check all recording rules are named correctly

### ISSUE THREAD

**Issue by mshahzeb** [grafana/dashboard-linter#58]
See https://prometheus.io/docs/practices/rules/

**Comment by v-zhuravlev** [comment]
that probably should go to `mixtool lint`?
https://github.com/monitoring-mixins/mixtool

**Comment by rgeyer** [comment]
Closing, as this does belong in mixtool.

Mixtool might get updated to use [pint](https://cloudflare.github.io/pint/), but this sort of checking can also be done directly with pint.
